services:
  - type: web
    name: aahaara-360-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /admin/
